name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_NAME: 'Hello'
  SRC_PATH: 'src' 
  OUTPUT_PATH: 'output' 
  DEPLOY_PATH: 'deploy' 
  DOTNET_VERSION: '7.0.x' 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Install dependencies
        run: dotnet restore ${{ env.SRC_PATH }}/Hello.sln
      
      - name: Build
        run: dotnet build ${{ env.SRC_PATH }}/Hello.sln --configuration Release --no-restore 

      - name: Publish
        run: dotnet publish ${{ env.SRC_PATH }}/Hello/Hello.csproj --no-build --no-restore --configuration Release --output ${{ env.OUTPUT_PATH }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Provision Resource Group
        run: |
          if [ $(az group exists --name "${{ env.APP_NAME }}-WUS") = false ]; then
            az group create --name "${{ env.APP_NAME }}-WUS" --location "West US"
          fi 

      - name: Provision Resources
        id: deploy
        uses: azure/arm-deploy@v1
        with:
          template: ${{ env.DEPLOY_PATH }}/azuredeploy.json
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "${{ env.APP_NAME }}-WUS"
          deploymentName: hello-1.0.${{github.run_number}}
      
      - name: Deploy
        uses: azure/webapps-deploy@v2
        id: fa
        with:
          app-name: ${{steps.deploy.outputs.siteName}}
          slot-name: 'Production'
          package: '${{ env.OUTPUT_PATH }}'
    
      - name: Test
        run: dotnet test ${{ env.SRC_PATH }}/Hello.sln --configuration Release --no-build --no-restore 
        env:
          WEBSITE: ${{steps.deploy.outputs.url}}


      





      